"""initial schema - all tables

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-07-25 00:00:00

This was hand-written from the SQLAlchemy models in app/models/, not
autogenerated - there's no live database in this environment to run
`alembic revision --autogenerate` against. Double-check it against your
actual MySQL version (this targets utf8mb4 / InnoDB defaults) before running
it against a database that matters, and diff it against a fresh
autogenerate once you have a real DB connection, just in case.

Mirrors schema.sql exactly - same tables, same order, same constraints.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _timestamps():
    """created_at/updated_at pair used on every table (TimestampMixin)."""
    return [
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
    ]


def _soft_delete():
    """deleted_at column used by every table with SoftDeleteMixin."""
    return [sa.Column("deleted_at", sa.DateTime(), nullable=True)]


def upgrade() -> None:
    # -- users -----------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=True),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("password", sa.String(255), nullable=True),
        sa.Column("cellphone", sa.String(32), nullable=True),
        sa.Column("otp", sa.String(16), nullable=True),
        sa.Column("login_token", sa.String(255), nullable=True),
        sa.Column("is_admin", sa.SmallInteger(), nullable=False, server_default="0"),
        *_timestamps(),
        *_soft_delete(),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("cellphone", name="uq_users_cellphone"),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    # -- access_tokens -----------------------------------------------------
    op.create_table(
        "access_tokens",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("token_hash", sa.String(255), nullable=False),
        sa.Column("name", sa.String(255), nullable=False, server_default="myApp"),
        sa.Column("abilities", sa.JSON(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("token_hash", name="uq_access_tokens_token_hash"),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_access_tokens_user_id", "access_tokens", ["user_id"])

    # -- provinces / cities ------------------------------------------------
    op.create_table(
        "provinces",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("province_id", sa.Integer(), sa.ForeignKey("provinces.id", ondelete="CASCADE"), nullable=False),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_cities_province_id", "cities", ["province_id"])

    # -- categories (car body types: sedan, SUV, ...) -----------------------
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("parent_id", sa.Integer(), sa.ForeignKey("categories.id", ondelete="SET NULL"), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.String(255), nullable=True),
        sa.Column("image", sa.String(255), nullable=True),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_categories_parent_id", "categories", ["parent_id"])

    # -- user_addresses ------------------------------------------------------
    op.create_table(
        "user_addresses",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("address", sa.String(255), nullable=False),
        sa.Column("cellphone", sa.String(32), nullable=False),
        sa.Column("postal_code", sa.String(32), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("province_id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_user_addresses_user_id", "user_addresses", ["user_id"])

    # -- brands ----------------------------------------------------------
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(255), nullable=False),
        sa.Column("logo", sa.String(255), nullable=True),
        *_timestamps(),
        *_soft_delete(),
        sa.UniqueConstraint("name", name="uq_brands_name"),
        sa.UniqueConstraint("slug", name="uq_brands_slug"),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    # -- cars / car_images ------------------------------------------------
    # replaces products / product_images / product_colors / product_sizes.
    # Each row is ONE physical car - color/price live directly here since
    # there's no quantity/stock concept (see inquiries below for the
    # delete-on-sale behavior)
    op.create_table(
        "cars",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(255), nullable=False),
        sa.Column("brand_id", sa.Integer(), sa.ForeignKey("brands.id", ondelete="CASCADE"), nullable=False),
        sa.Column("category_id", sa.Integer(), sa.ForeignKey("categories.id", ondelete="CASCADE"), nullable=False),
        sa.Column("model_name", sa.String(255), nullable=False),
        sa.Column("model_year", sa.Integer(), nullable=False),
        sa.Column("condition", sa.SmallInteger(), nullable=False, server_default="1"),  # 0 used, 1 new
        sa.Column("mileage_km", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("vin", sa.String(64), nullable=True),
        sa.Column("color", sa.String(32), nullable=False),  # one of app.core.car_constants.STANDARD_COLORS
        sa.Column("color_code", sa.String(32), nullable=False),
        sa.Column("transmission", sa.String(16), nullable=False, server_default="manual"),
        sa.Column("fuel_type", sa.String(16), nullable=False, server_default="gasoline"),
        sa.Column("chassis_healthy", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("body_healthy", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("primary_image", sa.String(255), nullable=False),
        sa.Column("primary_image_blurDataURL", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", sa.SmallInteger(), nullable=False, server_default="1"),
        sa.Column("sale_price", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("date_on_sale_from", sa.DateTime(), nullable=True),
        sa.Column("date_on_sale_to", sa.DateTime(), nullable=True),
        *_timestamps(),
        *_soft_delete(),
        sa.UniqueConstraint("slug", name="uq_cars_slug"),
        sa.UniqueConstraint("vin", name="uq_cars_vin"),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_cars_brand_id", "cars", ["brand_id"])
    op.create_index("ix_cars_category_id", "cars", ["category_id"])

    op.create_table(
        "car_images",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("car_id", sa.Integer(), sa.ForeignKey("cars.id", ondelete="CASCADE"), nullable=False),
        sa.Column("image", sa.String(255), nullable=False),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_car_images_car_id", "car_images", ["car_id"])

    # -- inquiries ---------------------------------------------------------
    # replaces orders / order_items / coupons / shipping_methods /
    # transactions - no online payment or cart checkout, just a request
    # that a sales agent follows up on by phone. Each car is a single
    # physical unit (no quantity) - closing a deal (status 4) deletes the
    # `cars` row, so car_id is nullable/SET NULL and car_title/car_price/
    # car_image are snapshotted here at creation time.
    op.create_table(
        "inquiries",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("car_id", sa.Integer(), sa.ForeignKey("cars.id", ondelete="SET NULL"), nullable=True),
        sa.Column("car_title", sa.String(255), nullable=False),
        sa.Column("car_price", sa.Integer(), nullable=False),
        sa.Column("car_image", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column("phone", sa.String(32), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("preferred_contact_time", sa.String(255), nullable=True),
        # 0 pending, 1 contacted, 2 negotiating, 3 test-drive scheduled,
        # 4 deal closed / sold, 5 cancelled, 6 rejected
        sa.Column("status", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_inquiries_user_id", "inquiries", ["user_id"])
    op.create_index("ix_inquiries_car_id", "inquiries", ["car_id"])

    # -- contact_us / sliders / stories -------------------------------------
    op.create_table(
        "contact_us",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("subject", sa.String(255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    op.create_table(
        "sliders",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("title", sa.String(255), nullable=True),
        sa.Column("file", sa.String(255), nullable=False),
        sa.Column("link", sa.String(255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("sort", sa.SmallInteger(), nullable=False, server_default="0"),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    op.create_table(
        "stories",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("title", sa.String(255), nullable=True),
        sa.Column("type", sa.Enum("image", "video", name="story_type"), nullable=False),
        sa.Column("file", sa.String(255), nullable=False),
        sa.Column("thumbnail", sa.String(255), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("link_url", sa.String(255), nullable=True),
        sa.Column("link_label", sa.String(255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("sort", sa.SmallInteger(), nullable=False, server_default="0"),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        *_timestamps(),
        *_soft_delete(),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    # -- favorites -----------------------------------------------------------
    # a simple saved-cars wishlist; replaces carts / cart_items - there's
    # no quantity or checkout to track, just "did the user save this listing"
    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("car_id", sa.Integer(), sa.ForeignKey("cars.id", ondelete="CASCADE"), nullable=False),
        *_timestamps(),
        sa.UniqueConstraint("user_id", "car_id", name="uq_favorite_user_car"),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )


def downgrade() -> None:
    op.drop_table("favorites")
    op.drop_table("stories")
    op.drop_table("sliders")
    op.drop_table("contact_us")
    op.drop_table("inquiries")
    op.drop_table("car_images")
    op.drop_table("cars")
    op.drop_table("brands")
    op.drop_table("user_addresses")
    op.drop_table("categories")
    op.drop_table("cities")
    op.drop_table("provinces")
    op.drop_table("access_tokens")
    op.drop_table("users")
